/*
 * generated by Xtext 2.9.2
 */
package de.esserjan.edu.xtext.tests

import com.google.inject.Inject
import de.esserjan.edu.xtext.fregeLang.Program
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

import static org.junit.Assert.*

@RunWith(XtextRunner)
@InjectWith(FregeLangInjectorProvider)
class FregeLangParsingTest {

//	@Inject
//	ParseHelper<Module> parseHelper;

	@Inject
	ParseHelper<Program> programParser;

	@Test
	def void testHelloWorld() {
		val result = programParser.parse('''
		module First where
		
		main = println "Hello world"		''')

		assertTrue(result.prg.contains('First'))
//		assertEquals(
//			"module 'First' expected.",
//			"First",
//			result.moduleId
//		)
 	}
}
