/*
 * generated by Xtext 2.9.2
 */
package de.esserjan.edu.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FregeLangRuntimeModule extends AbstractFregeLangRuntimeModule {
}
