/*
 * generated by Xtext 2.9.2
 */
package de.esserjan.edu.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FregeLangProposalProvider extends AbstractFregeLangProposalProvider {
}
